name: BirdBoard Workflow
on: [push, pull_request]

jobs:
    build:
        name: Build Application
        runs-on: ubuntu-16.04
        steps:
            - uses: actions/checkout@v1
            - uses: ./.github/actions/composer
            - uses: ./.github/actions/setup-laravel
            - uses: vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --stop-on-violation --using-cache=no
            - run: ./vendor/bin/phpunit --testdox
