name: BirdBoard Workflow
on: [push, pull_request]

jobs:
    build:
        name: Build Application
        runs-on: ubuntu-16.04
        steps:
            - uses: actions/checkout@v1
            - uses: ./.github/actions/composer
